// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: cr.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CRService_Election_FullMethodName = "/cr.CRService/Election"
	CRService_Elected_FullMethodName  = "/cr.CRService/Elected"
	CRService_Ping_FullMethodName     = "/cr.CRService/Ping"
)

// CRServiceClient is the client API for CRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The CR service definition.
type CRServiceClient interface {
	// Election RPC to start the election process.
	Election(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Elected RPC to notify the node that it has been elected.
	Elected(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Ping RPC to check if the node is alive.
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type cRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCRServiceClient(cc grpc.ClientConnInterface) CRServiceClient {
	return &cRServiceClient{cc}
}

func (c *cRServiceClient) Election(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CRService_Election_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRServiceClient) Elected(ctx context.Context, in *Message, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CRService_Elected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRServiceClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CRService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRServiceServer is the server API for CRService service.
// All implementations must embed UnimplementedCRServiceServer
// for forward compatibility.
//
// The CR service definition.
type CRServiceServer interface {
	// Election RPC to start the election process.
	Election(context.Context, *Message) (*emptypb.Empty, error)
	// Elected RPC to notify the node that it has been elected.
	Elected(context.Context, *Message) (*emptypb.Empty, error)
	// Ping RPC to check if the node is alive.
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	mustEmbedUnimplementedCRServiceServer()
}

// UnimplementedCRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCRServiceServer struct{}

func (UnimplementedCRServiceServer) Election(context.Context, *Message) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Election not implemented")
}
func (UnimplementedCRServiceServer) Elected(context.Context, *Message) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Elected not implemented")
}
func (UnimplementedCRServiceServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCRServiceServer) mustEmbedUnimplementedCRServiceServer() {}
func (UnimplementedCRServiceServer) testEmbeddedByValue()                   {}

// UnsafeCRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRServiceServer will
// result in compilation errors.
type UnsafeCRServiceServer interface {
	mustEmbedUnimplementedCRServiceServer()
}

func RegisterCRServiceServer(s grpc.ServiceRegistrar, srv CRServiceServer) {
	// If the following call pancis, it indicates UnimplementedCRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CRService_ServiceDesc, srv)
}

func _CRService_Election_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRServiceServer).Election(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRService_Election_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRServiceServer).Election(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRService_Elected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRServiceServer).Elected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRService_Elected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRServiceServer).Elected(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRServiceServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CRService_ServiceDesc is the grpc.ServiceDesc for CRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cr.CRService",
	HandlerType: (*CRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Election",
			Handler:    _CRService_Election_Handler,
		},
		{
			MethodName: "Elected",
			Handler:    _CRService_Elected_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _CRService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cr.proto",
}
